config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users

  authenticated :user do
    resource :subscription
    resources :logs
    resources :flights
  end

  mount_griddler('/email/inbound')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/airfield.rb
class Airfield < ApplicationRecord
  include PgSearch
  pg_search_scope :search_full_text, against: {
    name:   'A',
    city: 'B'
  }, :using => [:tsearch, :trigram]


  acts_as_mappable :default_units => :nms,
    :default_formula => :sphere,
    :distance_field_name => :distance,
    :lat_column_name => :lat,
    :lng_column_name => :lon
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flight.rb
class Flight < ApplicationRecord
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_save :generate_skydemon_key
  has_many :logs

  validates :skydemon_key, uniqueness: true

  private

  def generate_skydemon_key
    self.skydemon_key = SecureRandom.hex[0..8] unless skydemon_key
  end
  
end

app/controllers/airfields_controller.rb
class AirfieldsController < ApplicationController
  before_action :set_airfield, only: [:show, :edit, :update, :destroy]

  # GET /airfields
  # GET /airfields.json
  def index
    @airfields = Airfield.all
  end

  # GET /airfields/1
  # GET /airfields/1.json
  def show
  end

  # GET /airfields/new
  def new
    @airfield = Airfield.new
  end

  # GET /airfields/1/edit
  def edit
  end

  # POST /airfields
  # POST /airfields.json
  def create
    @airfield = Airfield.new(airfield_params)

    respond_to do |format|
      if @airfield.save
        format.html { redirect_to @airfield, notice: 'Airfield was successfully created.' }
        format.json { render :show, status: :created, location: @airfield }
      else
        format.html { render :new }
        format.json { render json: @airfield.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airfields/1
  # PATCH/PUT /airfields/1.json
  def update
    respond_to do |format|
      if @airfield.update(airfield_params)
        format.html { redirect_to @airfield, notice: 'Airfield was successfully updated.' }
        format.json { render :show, status: :ok, location: @airfield }
      else
        format.html { render :edit }
        format.json { render json: @airfield.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airfields/1
  # DELETE /airfields/1.json
  def destroy
    @airfield.destroy
    respond_to do |format|
      format.html { redirect_to airfields_url, notice: 'Airfield was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airfield
      @airfield = Airfield.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def airfield_params
      params.require(:airfield).permit(:icao, :iata, :name, :city, :state, :elevation, :lat, :lon)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  def index
    @flights = Flight.all
  end

  def show
  end

  def new
    @flight = Flight.new
  end

  def edit
  end

  def create
    @flight = Flight.new(Flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @flight.update(Flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_flight
    @flight = Flight.find(params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
     if user_signed_in?
      redirect_to logs_path
    end
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_log, only: [:show, :edit, :update, :destroy]

  # GET /logs
  # GET /logs.json
  def index
    @logs = Log.all
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
  end

  # GET /logs/new
  def new
    @log = Log.new
  end

  # GET /logs/1/edit
  def edit
  end

  # POST /logs
  # POST /logs.json
  def create
    @log = Log.new(log_params)

    respond_to do |format|
      if @log.save
        format.html { redirect_to @log, notice: 'Log was successfully created.' }
        format.json { render :show, status: :created, location: @log }
      else
        format.html { render :new }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logs/1
  # PATCH/PUT /logs/1.json
  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to @log, notice: 'Log was successfully updated.' }
        format.json { render :show, status: :ok, location: @log }
      else
        format.html { render :edit }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @log.destroy
    respond_to do |format|
      format.html { redirect_to logs_url, notice: 'Log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log
      @log = Log.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def log_params
      params.require(:log).permit(:aircraft, :reg, :start, :stop, :captain, :capacity, :from, :to)
    end

  private

  def requires_subscription?(user)
    user.billing_status.eql?("subscribed")
    user.logs.count < 10
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def new

  end

  def create
    stripe_token = params[:stripeToken]
    customer = Stripe::Customer.create(
      source: stripe_token,
      plan: "plan_DJiwGf0hxuvrDT",
      email: current_user.email,
    )
    current_user.customer_id = customer.id
    current_user.billing_status = "subscribed"
    current_user.save!
    redirect_to "/"
  end
end

app/helpers/airfields_helper.rb
module AirfieldsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/home/index.html.erb
<h1>Digiwings</h1>
<p>Automatically fill your logbook with flightaware or Skydemon logs</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Digiwings</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
    <script type="text/javascript">
      Stripe.setPublishableKey('<%= Rails.application.credentials.dig(Rails.env.to_sym, :stripe_public_key) %>');
  </script>
  </head>

  <body>
    <ul class="hmenu">
      <%= render 'devise/menu/registration_items' %>
      <%= render 'devise/menu/login_items' %>
    </ul>
    <%= yield %>
    <% if Rails.env.production? %>
    <!--Start of Zendesk Chat Script-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute("charset","utf-8");
$.src="https://v2.zopim.com/?5t5F3Ez4e9ArWNiD7JtPQD90CrDALsS0";z.t=+new Date;$.
type="text/javascript";e.parentNode.insertBefore($,e)})(document,"script");
</script>
<!--End of Zendesk Chat Script-->
  </body>
</html>
<% end %>

app/views/logs/_form.html.erb
<%= form_with(model: log, local: true) do |form| %>
  <% if log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
      <% log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :aircraft %>
    <%= form.text_field :aircraft %>
  </div>

  <div class="field">
    <%= form.label :reg %>
    <%= form.text_field :reg %>
  </div>

  <div class="field">
    <%= form.label :start %>
    <%= form.time_select :start %>
  </div>

  <div class="field">
    <%= form.label :stop %>
    <%= form.time_select :stop %>
  </div>

  <div class="field">
    <%= form.label :captain %>
    <%= form.text_field :captain %>
  </div>

  <div class="field">
    <%= form.label :capacity %>
    <%= form.text_field :capacity %>
  </div>

  <div class="field">
    <%= form.label :from %>
    <%= form.text_field :from %>
  </div>

  <div class="field">
    <%= form.label :to %>
    <%= form.text_field :to %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/logs/edit.html.erb
<h1>Editing Log</h1>

<%= render 'form', log: @log %>

<%= link_to 'Show', @log %> |
<%= link_to 'Back', logs_path %>

app/views/logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Logs</h1>

<table>
  <thead>
    <tr>
      <th>Aircraft</th>
      <th>Reg</th>
      <th>Start</th>
      <th>Stop</th>
      <th>Captain</th>
      <th>Capacity</th>
      <th>From</th>
      <th>To</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logs.each do |log| %>
      <tr>
        <td><%= log.aircraft %></td>
        <td><%= log.reg %></td>
        <td><%= log.start %></td>
        <td><%= log.stop %></td>
        <td><%= log.captain %></td>
        <td><%= log.capacity %></td>
        <td><%= log.from %></td>
        <td><%= log.to %></td>
        <td><%= link_to 'Show', log %></td>
        <td><%= link_to 'Edit', edit_log_path(log) %></td>
        <td><%= link_to 'Destroy', log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Log', new_log_path %>

app/views/logs/new.html.erb
<h1>New Log</h1>

<%= render 'form', log: @log %>

<%= link_to 'Back', logs_path %>

app/views/logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Aircraft:</strong>
  <%= @log.aircraft %>
</p>

<p>
  <strong>Reg:</strong>
  <%= @log.reg %>
</p>

<p>
  <strong>Start:</strong>
  <%= @log.start %>
</p>

<p>
  <strong>Stop:</strong>
  <%= @log.stop %>
</p>

<p>
  <strong>Captain:</strong>
  <%= @log.captain %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @log.capacity %>
</p>

<p>
  <strong>From:</strong>
  <%= @log.from %>
</p>

<p>
  <strong>To:</strong>
  <%= @log.to %>
</p>

<%= link_to 'Edit', edit_log_path(@log) %> |
<%= link_to 'Back', logs_path %>

app/views/subscriptions/new.html.erb
<h2>Subscribe to digiwings</h2>

<%= form_tag({:controller => "subscriptions", :action => "create"}, :method => "post", :id => "new_subscriber") do |f| %>

  <span class="payment-errors"></span>

  <p>
    <%= label_tag "Card Number"%>
    <%= text_field_tag nil, nil, data: { stripe: "number" } %>
  </p>

  <p>
    <%= label_tag "Expiration (MM/YY)" %>
    <%= text_field_tag nil, nil, data: { stripe: "exp_month" }, size: 4 %>
    <span>/</span>
    <%= text_field_tag nil, nil, data: { stripe: "exp_year" }, size: 4 %>
  </p>

  <p>
    <%= label_tag "CVC"%>
    <%= text_field_tag nil, nil, data: { stripe: "cvc" }, size: 4 %>
  </p>

  <%= submit_tag "Submit Payment", class: "submit" %>

<% end %>

<script>
  $(function() {
  var $form = $('#new_subscriber');
  $form.submit(function(event) {
    // Disable the submit button to prevent repeated clicks:
    $form.find('.submit').prop('disabled', true);

    // Request a token from Stripe:
    Stripe.card.createToken($form, stripeResponseHandler);

    // Prevent the form from being submitted:
    return false;
  });
});

function stripeResponseHandler(status, response) {
  // Grab the form:
  var $form = $('#new_subscriber');

  if (response.error) { // Problem!

    // Show the errors on the form:
    $form.find('.payment-errors').text(response.error.message);
    $form.find('.submit').prop('disabled', false); // Re-enable submission

  } else { // Token was created!

    // Get the token ID:
    var token = response.id;

    // Insert the token ID into the form so it gets submitted to the server:
    $form.append($('<input type="hidden" name="stripeToken">').val(token));

    // Submit the form:
    $form.get(0).submit();
  }
};
</script>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>